pub mod tasreef;
pub mod musarrif;
pub mod generator;
pub mod runtime;
pub mod bayan_engine;
pub mod interpreter;
pub mod parser;
pub mod server;
pub mod ai;
pub mod game;
pub mod database;
pub mod optimizer;
pub mod balagha;
pub mod morphology;
pub mod roots_map;
pub mod orchestrator;
pub mod composer;
pub mod executor;
pub mod control;
pub mod variables;
pub mod functions;
pub mod exceptions;
pub mod loops;

pub const BAYAN_VERSION: &str = "0.5.0";
pub const BAYAN_NAME: &str = "البيان";
pub const BAYAN_SLOGAN: &str = "الكود قرآن - لغة الأم";
